BookApp/Models/LibraryViewModel.cs
using BookApp.Core.DTO;

namespace BookApp.Models
{
    public class LibraryViewModel
    {
        public List<BookViewModel> Books { get; set; } = new List<BookViewModel>();
        public List<CategoryDTO> CategoriyDTO { get; set; }

        public LibraryViewModel() { }

        public LibraryViewModel(List<CategoryDTO> categoriyDTO)
        {
            CategoriyDTO = categoriyDTO;
        }
    }

    public class BookViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Serie { get; set; }
        public string Genre { get; set; }
        public string ImageUrl { get; set; }
        
        public int UserId { get; set; }
        public List<CategoryViewModel> Categories { get; set; } = new List<CategoryViewModel>();
        public List<CategoryViewModel> AllCategories { get; set; } = new List<CategoryViewModel>();

        public class CategoryViewModel
        {
            public int Id { get; set; }
            public string Name { get; set; }
            public bool IsStandard { get; set; }
        }
    }
}

BookApp/Controllers/LibraryController.cs
using BookApp.Core.Interfaces;
using BookApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace BookApp.Controllers
{
    public class LibraryController : Controller
    {
        private readonly ILogger<LibraryController> _logger;
        private readonly IBookService _bookService;
        private readonly ICategoryService _categoryService;

        public LibraryController(ILogger<LibraryController> logger, IBookService bookService,
            ICategoryService categoryService)
        {
            _logger = logger;
            _bookService = bookService;
            _categoryService = categoryService;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                int? userId = HttpContext.Session.GetInt32("UserId");
                if (!userId.HasValue)
                {
                    return RedirectToAction("Index", "Home");
                }

                var booksInLibrary = await _bookService.GetBooksByUserIdAsync(userId.Value);

                if (booksInLibrary == null || !booksInLibrary.Any())
                {
                    _logger.LogInformation("No books found in the library.");
                    return View(new LibraryViewModel { Books = new List<BookViewModel>() });
                }

                _logger.LogInformation($"Found {booksInLibrary.Count()} books in the library.");

                var booksViewModel = booksInLibrary.Select(book => new BookViewModel
                {
                    Title = book.Title,
                    Author = book.Author,
                    ImageUrl = book.ImageUrl
                }).ToList();

                return View(new LibraryViewModel { Books = booksViewModel });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "An error occurred while processing the index action.");
                return View(new LibraryViewModel { Books = new List<BookViewModel>() });
            }
        }

        public async Task<IActionResult> BookDetails(string title)
        {
            if (string.IsNullOrEmpty(title))
            {
                return BadRequest("Book title cannot be null or empty.");
            }

            int? userId = HttpContext.Session.GetInt32("UserId");
            if (!userId.HasValue)
            {
                return RedirectToAction("Index", "Home");
            }

            var book = await _bookService.GetBookByTitleAsync(title);

            if (book == null)
            {
                return NotFound("Book not found.");
            }

            var bookCategories = await _bookService.GetCategoriesByBookIdAsync(userId.Value, book.Id);
            var allCategories = await _categoryService.GetAllCategoriesAsync();

            var bookViewModel = new BookViewModel
            {
                Id = book.Id,
                Title = book.Title,
                Author = book.Author,
                Serie = book.Serie,
                Genre = book.Genre,
                ImageUrl = book.ImageUrl,
                Categories = bookCategories.Select(c => new BookViewModel.CategoryViewModel
                {
                    Id = c.Id,
                    Name = c.Name,
                    IsStandard = c.IsStandard
                }).ToList(),
                AllCategories = allCategories.Select(c => new BookViewModel.CategoryViewModel
                {
                    Id = c.Id,
                    Name = c.Name,
                    IsStandard = c.IsStandard
                }).ToList()
            };

            return View(bookViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteBook(string title)
        {
            int? userId = HttpContext.Session.GetInt32("UserId");
            if (!userId.HasValue)
            {
                return RedirectToAction("Index", "Home");
            }

            if (string.IsNullOrEmpty(title))
            {
                return BadRequest("Book title cannot be null or empty.");
            }

            var book = await _bookService.GetBookByTitleAsync(title);

            if (book == null)
            {
                return NotFound("Book not found.");
            }

            await _bookService.DeleteBookByTitleAsync(title, userId.Value);
            await _bookService.DeleteUserBookByBookIdAsync(book.Id, userId.Value);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> SaveCategory(int bookId, int categoryId)
        {
            if (categoryId <= 0)
            {
                return BadRequest("First category must be chosen.");
            }

            try
            {
                await _categoryService.SaveCategoryAsync(bookId, categoryId, categoryId);
                return Ok();
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "An error occurred while saving the category.");
                return StatusCode(500, "Internal server error");
            }
        }
    }
}

BookApp/Views/Library/BookDetails.cshtml
@model BookApp.Models.BookViewModel

<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/BookDetails.css" asp-append-version="true"/>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500&display=swap" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<body>
<div class="Book">
    <div class="BookImage">
        <img src="@Model.ImageUrl" class="BookImage" alt="Cover image of @Model.Title"/>
    </div>
    <div class="BookTitle">
        <p>@Model.Title</p>
    </div>
    <div class="BookAuthor">
        <p>@Model.Author</p>
    </div>
    <div class="BookSeries">
        <p>Series: @Model.Serie</p>
    </div>
    <div class="BookGenre">
        <p>Genre: @Model.Genre</p>
    </div>
   <div class="BookCategories">
       <p>Categories:</p>
       <ul>
           @foreach (var category in Model.Categories)
           {
               <li class="categories">
                   <span>@category.Name</span>
                   <i class="fas fa-edit" onclick="toggleEditCategory(this)"></i>
                   @if (category.IsStandard)
                   {
                       <select name="standardCategoryIds" class="category-dropdown" style="display:none;">
                           @foreach (var cat in Model.AllCategories.Where(c => c.IsStandard))
                           {
                               <option value="@cat.Id">@cat.Name</option>
                           }
                       </select>
                   }
                   else
                   {
                       <select name="nonStandardCategoryIds" class="category-dropdown" style="display:none;">
                           @foreach (var cat in Model.AllCategories.Where(c => !c.IsStandard))
                           {
                               <option value="@cat.Id">@cat.Name</option>
                           }
                       </select>
                   }
               </li>
           }

       </ul>
   </div>


</div>

<form id="deleteBookForm" method="post" action="@Url.Action("DeleteBook", "Library")">
    <input type="hidden" name="title" value="@Model.Title"/>
    <button type="submit" class="DeleteBookButton"><i class="fa-solid fa-trash-can"></i>Delete book</button>
</form>

<script>
    // Display confirmation dialog before submitting delete form
    document.querySelector('.DeleteBookButton').addEventListener('click', function (event) {
            event.preventDefault();
            var title = document.querySelector('.BookTitle p').textContent.trim(); // Fetch the book title
            Swal.fire({
                title: 'Are you sure?',
                text: `The book "${title}" will be deleted from your library.`,
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    document.getElementById('deleteBookForm').submit();
                }
            });
        });
    
    function toggleEditCategory(icon) {
        var categoryElement = icon.parentElement;
        var spans = categoryElement.querySelectorAll('span');
        var selects = categoryElement.querySelectorAll('select');
    
        for (var i = 0; i < spans.length; i++) {
            if (selects[i].style.display === 'none') {
                spans[i].style.display = 'none';
                selects[i].style.display = 'inline';
                icon.classList.remove('fa-edit');
                icon.classList.add('fa-save');
            } else {
                spans[i].style.display = 'inline';
                selects[i].style.display = 'none';
                icon.classList.remove('fa-save');
                icon.classList.add('fa-edit');
                spans[i].innerText = selects[i].options[selects[i].selectedIndex].text;
                
                // Get the selected category ID
                var categoryId = selects[i].value;
                var bookId = '@Model.Id'; // Get the book ID from the model
    
                // Make an AJAX request to update the book's category
                saveCategory(bookId, categoryId);
            }
        }
    }
    
    function saveCategory(bookId, categoryId) {
        return new Promise((resolve, reject) => {
            $.ajax({
                type: 'POST',
                url: '/Library/SaveCategory', // Update the URL with your controller action
                data: { userBookId: bookId, categoryId1: categoryId, categoryId2: 0 }, // Assuming categoryId2 is always 0 for now
                success: function (response) {
                    resolve(true);
                },
                error: function (xhr, status, error) {
                    reject(false);
                }
            });
        });
    }

</script>

</body>
</html>

BookApp/Views/Library/Index.cshtml
@model BookApp.Models.LibraryViewModel

@{
    ViewData["Title"] = "Your Library";
}

<!DOCTYPE html>
<html>
<head>
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/Library.css" asp-append-version="true"/>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500&display=swap" rel="stylesheet">
</head>
<body>
<div class="grid-container">
    @foreach (var book in Model.Books)
    {
        <div class="grid-item">
            <a href="@Url.Action("BookDetails", "Library", new { title = book.Title })">
                <div class="BookImage">
                    <img src="@book.ImageUrl" class="BookImage"/>
                </div>
                <div class="BookTitle">
                    <p>@book.Title</p>
                </div>
                <div class="BookAuthor">
                    <p>@book.Author</p>
                </div>
                @* <div class="BookCategories"> *@
                @*     <p>Categories:</p> *@
                @*     <ul> *@
                @*         @foreach (var category in book.Categories) *@
                @*         { *@
                @*             <li>@category.Name)</li> *@
                @*         } *@
                @*     </ul> *@
                @* </div> *@
            </a>
        </div>
    }
</div>
</body>
</html>